version: "3.8"

services:

  # API Gateway
  api-gateway:
    build:
      context: ./services/api-gateway
      dockerfile: Dockerfile
    ports:
      - "8080:8080" # единственный порт снаружи
    environment:
      - PORT=8080
      - REDIS_URL=redis://redis:6379
      - TRANSACTION_SERVICE_URL=http://transaction-service:8080
      - DEFAULT_RATE_LIMIT=100
      - LOG_LEVEL=debug
    depends_on:
      redis:
        condition: service_healthy
      redis-seed:
        condition: service_completed_successfully
      transaction-service:
        condition: service_healthy
    restart: on-failure
    healthcheck:
      test: ["CMD-SHELL", "wget -qO- http://localhost:8080/health || exit 1"]
      interval: 10s
      timeout: 3s
      retries: 3
      start_period: 10s

  # Transaction Service
  transaction-service:
    build:
      context: ./services/transaction-service
      dockerfile: Dockerfile
    # ports не указываем — снаружи недоступен
    environment:
      - SERVER_PORT=8080
      - DB_HOST=postgres
      - DB_PORT=5432
      - DB_USER=payment
      - DB_PASSWORD=payment_secret
      - DB_NAME=payment_gateway
      - REDIS_ADDR=redis:6379
      - NATS_URL=nats://nats:4222
      - LOG_LEVEL=debug
    depends_on:
      postgres:
        condition: service_healthy
      redis:
        condition: service_healthy
      nats:
        condition: service_healthy
    restart: on-failure
    healthcheck:
      test: ["CMD-SHELL", "wget -qO- http://localhost:8080/health || exit 1"]
      interval: 10s
      timeout: 3s
      retries: 3
      start_period: 10s

  # Risk Service
  risk-service:
    build:
      context: ./services/risk-service
      dockerfile: Dockerfile
    environment:
      - PORT=8083
      - REDIS_URL=redis://redis:6379
      - NATS_URL=nats://nats:4222
      - RULES_PATH=/app/rules/default.json
      - LOG_LEVEL=debug
    depends_on:
      redis:
        condition: service_healthy
      nats:
        condition: service_healthy
    restart: on-failure
    healthcheck:
      test: ["CMD-SHELL", "wget -qO- http://localhost:8083/health || exit 1"]
      interval: 10s
      timeout: 3s
      retries: 3
      start_period: 10s

  # Provider Service
  provider-service:
    build:
      context: ./services/provider-service
      dockerfile: Dockerfile
    environment:
      - DB_HOST=postgres-provider
      - DB_PORT=5432
      - DB_USER=payment
      - DB_PASSWORD=payment_secret
      - DB_NAME=provider_db
      - SERVER_PORT=8082
      - NATS_URL=nats://nats:4222
      - REDIS_ADDR=redis:6379
      - REDIS_DB=1
      - LOG_LEVEL=debug
    depends_on:
      postgres-provider:
        condition: service_healthy
      nats:
        condition: service_healthy
      redis:
        condition: service_healthy
      risk-service:
        condition: service_healthy
    restart: on-failure

  # Redis Seed
  # Init-контейнер: создаёт тестовые API-ключи при старте.
  # restart: no — запускается один раз и завершается.
  # api-gateway ждёт его через condition: service_completed_successfully.
  redis-seed:
    image: redis:7-alpine
    depends_on:
      redis:
        condition: service_healthy
    restart: "no"
    entrypoint:
      - sh
      - -c
      - |
        KEY1=$$(echo -n "test_key_merchant_1" | sha256sum | cut -d" " -f1)
        KEY2=$$(echo -n "test_key_merchant_2" | sha256sum | cut -d" " -f1)

        redis-cli -h redis HSET apikeys:$$KEY1 merchant_id merchant_001 name "Test_Merchant_1" rate_limit 100 active true
        redis-cli -h redis HSET apikeys:$$KEY2 merchant_id merchant_002 name "Test_Merchant_2" rate_limit 50 active true

        echo "Redis seed completed"

  # PostgreSQL — transaction-service
  postgres:
    image: postgres:16-alpine
    environment:
      POSTGRES_USER: payment
      POSTGRES_PASSWORD: payment_secret
      POSTGRES_DB: payment_gateway
    volumes:
      - postgres_data:/var/lib/postgresql/data
      - ./services/transaction-service/migrations:/docker-entrypoint-initdb.d
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U payment -d payment_gateway"]
      interval: 5s
      timeout: 3s
      retries: 5

  # PostgreSQL — provider-service
  postgres-provider:
    image: postgres:16-alpine
    environment:
      POSTGRES_USER: payment
      POSTGRES_PASSWORD: payment_secret
      POSTGRES_DB: provider_db
    volumes:
      - postgres_provider_data:/var/lib/postgresql/data
      - ./services/provider-service/migrations:/docker-entrypoint-initdb.d
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U payment -d provider_db"]
      interval: 5s
      timeout: 3s
      retries: 5

  # Redis
  redis:
    image: redis:7-alpine
    healthcheck:
      test: ["CMD", "redis-cli", "ping"]
      interval: 5s
      timeout: 3s
      retries: 5

  # NATS JetStream
  nats:
    image: nats:2.10-alpine
    command: ["-js", "-m", "8222"]
    ports:
      - "4222:4222"
      - "8222:8222"
    healthcheck:
      test: ["CMD-SHELL", "wget -q --spider http://localhost:8222/healthz || exit 1"]
      interval: 5s
      timeout: 3s
      retries: 5
  
  prometheus:
    image: prom/prometheus:v2.51.0
    volumes:
      - ./monitoring/prometheus.yml:/etc/prometheus/prometheus.yml
      - prometheus_data:/prometheus
    ports:
      - "9090:9090"
    command:
      - '--config.file=/etc/prometheus/prometheus.yml'
      - '--storage.tsdb.path=/prometheus'
      - '--web.enable-lifecycle'  # позволяет reload конфига без рестарта
    restart: on-failure

  grafana:
    image: grafana/grafana:10.4.0
    ports:
      - "3000:3000"
    environment:
      - GF_SECURITY_ADMIN_PASSWORD=admin
      - GF_USERS_ALLOW_SIGN_UP=false
    volumes:
      - ./monitoring/grafana/provisioning:/etc/grafana/provisioning
      - grafana_data:/var/lib/grafana
    depends_on:
      - prometheus
    restart: on-failure

volumes:
  grafana_data:
  prometheus_data:
  postgres_data:
  postgres_provider_data:
